"""
Dungeon Cortex — Shared Database Schema (§5)
SQLModel definitions serving as both Pydantic validators and SQLAlchemy table definitions.
Second Law: State is Truth — these models ARE the game reality.
"""

from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4

from sqlmodel import Field, SQLModel, Column
from sqlalchemy import JSON


# ============================================================
# §5.1 — SRD Mechanics (Read-Only reference data)
# ============================================================

class SrdMechanic(SQLModel, table=True):
    """
    Source of Truth for D&D 5e rules (Read-Only).
    Populated by ETL from 5e-bits/5e-srd-api + Magical20-ai/5e-database-spanish.
    NEVER modified during gameplay.
    """
    __tablename__ = "srd_mechanic"

    id: str = Field(primary_key=True)              # e.g. "spell_fireball", "monster_goblin"
    type: str                                       # "monster", "spell", "item", "class_feature"

    # Raw data from 5e-bits/5e-srd-api (English)
    data_json: Dict = Field(default={}, sa_column=Column(JSON))

    # Localized data from Magical20-ai/5e-database-spanish
    data_es: Dict = Field(default={}, sa_column=Column(JSON))

    # TODO Phase 3: Add search_vector (TSVector) for full-text search


# ============================================================
# §5.2 — Character (Live Player State)
# ============================================================

class Character(SQLModel, table=True):
    """
    Living Avatar State — synchronized via AG-UI State Patches.
    Modified ONLY by validated Logic Core events.
    """
    __tablename__ = "character"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    name: str

    # Base Attributes (immutable except on Level Up)
    stats: Dict = Field(default={}, sa_column=Column(JSON))  # {str: 18, dex: 12, ...}

    # Live State (synced via AG-UI STATE_PATCH events)
    hp_current: int = 0
    hp_max: int = 0
    conditions: List[str] = Field(default=[], sa_column=Column(JSON))  # ["blinded", "poisoned"]

    # Spatial Location
    location_cell_id: int = 0           # Azgaar map cell reference
    active_scene_id: Optional[str] = None


# ============================================================
# §5.3 — Inventory (Positional Paper Doll)
# ============================================================

class ItemLocation(str, Enum):
    """Where an item physically exists in the game world."""
    EQUIPPED = "equipped"
    BACKPACK = "backpack"
    STASH = "stash"


class InventoryItem(SQLModel, table=True):
    """
    Physical instance of an object in the game world.
    Slot-based inventory forces tactical decisions.
    """
    __tablename__ = "inventory_item"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    character_id: UUID = Field(foreign_key="character.id")
    template_id: str = Field(foreign_key="srd_mechanic.id")

    # Visual & Positional Logic
    location: ItemLocation = ItemLocation.BACKPACK
    slot_type: Optional[str] = None     # "head", "main_hand", "torso", "ring_1"
    grid_index: Optional[int] = None    # 0-19 (backpack grid position)

    # Instance State
    current_charges: int = 0
    is_identified: bool = False
    custom_name: Optional[str] = None
    visual_asset_url: str = ""          # Generated by Visual Vault
